//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.TrainerIintrestedCourses = new HashSet<TrainerIintrestedCourse>();
        }
    
        public int Courseid { get; set; }
        public string Tittel { get; set; }
        public int Credits { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<Level> level { get; set; }
        public Nullable<bool> IsCourseActive { get; set; }
        public Nullable<Rating> Rating { get; set; }
        public Nullable<int> CourseLevelid { get; set; }
        public Nullable<int> Departmentid { get; set; }
    
        public virtual CourseLevel CourseLevel { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerIintrestedCourse> TrainerIintrestedCourses { get; set; }
    }
}
