//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_learning.Models
{
    using System;
    
    public enum Rating : byte
    {
        Fail = 1,
        bad = 2,
        good = 3,
        verygood = 4,
        high = 5
    }
}
