//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerIintrestedCourse
    {
        public int TrainerIntCoureseid { get; set; }
        public Nullable<int> Trainnerid { get; set; }
        public Nullable<int> Courseid { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Trainner Trainner { get; set; }
    }
}
