//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_learning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainner()
        {
            this.TrainerIintrestedCourses = new HashSet<TrainerIintrestedCourse>();
        }
    
        public int Trainnerid { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public string AspNerUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerIintrestedCourse> TrainerIintrestedCourses { get; set; }
    }
}
